# Generated by Django 4.2.11 on 2025-03-03 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('title_en', models.CharField(max_length=200, null=True, unique=True)),
                ('title_hi', models.CharField(max_length=200, null=True, unique=True)),
                ('title_ml', models.CharField(max_length=200, null=True, unique=True)),
                ('title_zh_cn', models.CharField(max_length=200, null=True, unique=True)),
                ('short_description', models.TextField()),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_hi', models.TextField(null=True)),
                ('short_description_ml', models.TextField(null=True)),
                ('short_description_zh_cn', models.TextField(null=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('content_en', models.TextField(null=True, verbose_name='Content')),
                ('content_hi', models.TextField(null=True, verbose_name='Content')),
                ('content_ml', models.TextField(null=True, verbose_name='Content')),
                ('content_zh_cn', models.TextField(null=True, verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('alt_text', models.TextField(blank=True, help_text='Alt text field for featured image', max_length=126, null=True)),
                ('alt_text_en', models.TextField(blank=True, help_text='Alt text field for featured image', max_length=126, null=True)),
                ('alt_text_hi', models.TextField(blank=True, help_text='Alt text field for featured image', max_length=126, null=True)),
                ('alt_text_ml', models.TextField(blank=True, help_text='Alt text field for featured image', max_length=126, null=True)),
                ('alt_text_zh_cn', models.TextField(blank=True, help_text='Alt text field for featured image', max_length=126, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('unpublished_on', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keyword', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='categories.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='tags.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='blog_videos/')),
                ('video_en', models.FileField(blank=True, null=True, upload_to='blog_videos/')),
                ('video_hi', models.FileField(blank=True, null=True, upload_to='blog_videos/')),
                ('video_ml', models.FileField(blank=True, null=True, upload_to='blog_videos/')),
                ('video_zh_cn', models.FileField(blank=True, null=True, upload_to='blog_videos/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('thumbnail', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='blog_videos_thumbnail/')),
                ('alt_text', models.TextField(blank=True, help_text='Alt text field for video thumbnail image', max_length=126, null=True)),
                ('alt_text_en', models.TextField(blank=True, help_text='Alt text field for video thumbnail image', max_length=126, null=True)),
                ('alt_text_hi', models.TextField(blank=True, help_text='Alt text field for video thumbnail image', max_length=126, null=True)),
                ('alt_text_ml', models.TextField(blank=True, help_text='Alt text field for video thumbnail image', max_length=126, null=True)),
                ('alt_text_zh_cn', models.TextField(blank=True, help_text='Alt text field for video thumbnail image', max_length=126, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slideshow_videos', to='blogs.blog')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('alt_text', models.TextField(blank=True, max_length=126, null=True)),
                ('alt_text_en', models.TextField(blank=True, max_length=126, null=True)),
                ('alt_text_hi', models.TextField(blank=True, max_length=126, null=True)),
                ('alt_text_ml', models.TextField(blank=True, max_length=126, null=True)),
                ('alt_text_zh_cn', models.TextField(blank=True, max_length=126, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slideshow_images', to='blogs.blog')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
