# Generated by Django 4.2.11 on 2025-03-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60, null=True)),
                ('name_hi', models.CharField(max_length=60, null=True)),
                ('name_ml', models.CharField(max_length=60, null=True)),
                ('name_zh_cn', models.CharField(max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_hi', models.TextField(blank=True, null=True)),
                ('description_ml', models.TextField(blank=True, null=True)),
                ('description_zh_cn', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('alt_text', models.TextField(blank=True, help_text='Alt text field for images in categories', max_length=126, null=True)),
                ('alt_text_en', models.TextField(blank=True, help_text='Alt text field for images in categories', max_length=126, null=True)),
                ('alt_text_hi', models.TextField(blank=True, help_text='Alt text field for images in categories', max_length=126, null=True)),
                ('alt_text_ml', models.TextField(blank=True, help_text='Alt text field for images in categories', max_length=126, null=True)),
                ('alt_text_zh_cn', models.TextField(blank=True, help_text='Alt text field for images in categories', max_length=126, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
