# Generated by Django 4.2.11 on 2025-03-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_hi', models.CharField(max_length=100, null=True, unique=True)),
                ('name_ml', models.CharField(max_length=100, null=True, unique=True)),
                ('name_zh_cn', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_hi', models.TextField(blank=True, null=True)),
                ('description_ml', models.TextField(blank=True, null=True)),
                ('description_zh_cn', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
