# Generated by Django 4.2.11 on 2025-03-03 20:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('name_hi', models.CharField(blank=True, max_length=50, null=True)),
                ('name_ml', models.CharField(blank=True, max_length=50, null=True)),
                ('name_zh_cn', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('address_en', models.CharField(blank=True, max_length=200, null=True)),
                ('address_hi', models.CharField(blank=True, max_length=200, null=True)),
                ('address_ml', models.CharField(blank=True, max_length=200, null=True)),
                ('address_zh_cn', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('logo_white', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Company setting',
                'verbose_name_plural': 'Company setting',
            },
        ),
        migrations.CreateModel(
            name='DropDownClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ml', models.CharField(blank=True, max_length=100, null=True)),
                ('name_zh_cn', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Drop Down',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('question_en', models.CharField(max_length=200, null=True)),
                ('question_hi', models.CharField(max_length=200, null=True)),
                ('question_ml', models.CharField(max_length=200, null=True)),
                ('question_zh_cn', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ml', models.CharField(blank=True, max_length=100, null=True)),
                ('name_zh_cn', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Faq Categories',
            },
        ),
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='eg.setting_name', max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, help_text='eg.setting_name', max_length=100, null=True)),
                ('name_hi', models.CharField(blank=True, help_text='eg.setting_name', max_length=100, null=True)),
                ('name_ml', models.CharField(blank=True, help_text='eg.setting_name', max_length=100, null=True)),
                ('name_zh_cn', models.CharField(blank=True, help_text='eg.setting_name', max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('description_en', models.TextField(blank=True, max_length=256, null=True)),
                ('description_hi', models.TextField(blank=True, max_length=256, null=True)),
                ('description_ml', models.TextField(blank=True, max_length=256, null=True)),
                ('description_zh_cn', models.TextField(blank=True, max_length=256, null=True)),
                ('value', models.TextField(blank=True, null=True, verbose_name='value')),
                ('value_en', models.TextField(blank=True, null=True, verbose_name='value')),
                ('value_hi', models.TextField(blank=True, null=True, verbose_name='value')),
                ('value_ml', models.TextField(blank=True, null=True, verbose_name='value')),
                ('value_zh_cn', models.TextField(blank=True, null=True, verbose_name='value')),
                ('is_public', models.BooleanField(blank=True, default=True, help_text='Should this value be accessible to the public/users')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Regulations',
                'verbose_name_plural': 'Regulations',
            },
        ),
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_en', models.CharField(max_length=255, null=True, unique=True)),
                ('title_hi', models.CharField(max_length=255, null=True, unique=True)),
                ('title_ml', models.CharField(max_length=255, null=True, unique=True)),
                ('title_zh_cn', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Static text',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='social_media/')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='statictext.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='FAQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_en', models.TextField(blank=True, null=True)),
                ('answer_hi', models.TextField(blank=True, null=True)),
                ('answer_ml', models.TextField(blank=True, null=True)),
                ('answer_zh_cn', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='statictext.faq')),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='statictext.faqcategory'),
        ),
        migrations.CreateModel(
            name='DropDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('value_en', models.CharField(blank=True, max_length=100, null=True)),
                ('value_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('value_ml', models.CharField(blank=True, max_length=100, null=True)),
                ('value_zh_cn', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropdowns', to='statictext.dropdownclass')),
            ],
        ),
    ]
